### ISSUE TITLE
Add JPEG and TrueType support in PHP

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#26]
```
parts:
  apache:
...
    third-party-modules:
...
        configflags:
...
          - --with-gd
          - --enable-gd-native-ttf
          - --with-jpeg-dir=/usr/lib
          - --with-freetype-dir=/usr/lib
    stage-packages:
...
      - libfontconfig1
      - libfreetype6
      - libjpeg8
    build-packages:
...
      - libgd-dev
```

@kyrofa - Please confirm that's the proper way to add the required dependencies. I've tested the config and it works.
