### ISSUE TITLE
Put customizations in customizations sub-folders and always use a source for the copy plugin

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#70]
In order to better organise source files, I propose the following part organisation

```
src
-- mysql
----customizations
------start_mysql
...
```

along with the following part structure

```
  # Copy over our MySQL scripts
  mysql-customizations:
    plugin: copy
    source: src/mysql/customizations
    files:
      # This one is what creates the initial database and account for ownCloud.
      start_mysql: bin/
      my.cnf: my.cnf
      mysql.server: support-files/
```

This will become more important as more parts are added to the snap.

@kyrofa
